version: "3.8"

services:
  database:
    image: postgres:15.0
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=indexes
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    # networks:
    #   - my-network

  roman_api:
    build:
      context: .
      dockerfile: dockerfile
    container_name: roman_converter
    depends_on: 
      - database
    env_file:
      - .env
    # networks:
    #   - my-network  
    ports:
    - "8000:8000" 

# networks:
#   my-network:  

volumes:
  pgdata:
