services:
  redis:
    image: redis:latest
    container_name: redis-server
    # ports:
    #   - 6379:6379
    volumes:
      - redis_data:/data
    networks:
      - my-network

  cli_roman:
    build:
      context: .
      dockerfile: dockerfile
    container_name: cli_roman
    networks:
      - my-network
    depends_on: 
      - redis

networks:
  my-network:

volumes:
  redis_data: